import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    DateTime,
    Enum as SAEnum,
    ForeignKey,
    Index,
    Integer,
    String,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.models.base import Base

if TYPE_CHECKING:
    from src.models.gallery import Gallery
    from src.models.user import User


class Photo(Base):
    """
    A single photo uploaded to a gallery.

    S3 storage layout (example):
      original : photos/{event_id}/{photo_id}/original.jpg
      thumbnail: photos/{event_id}/{photo_id}/thumb_400.jpg

    Thumbnails are ~400px on the longest side, generated by a background worker
    after upload. They are essential for gallery grid views: loading originals
    (often 4-10 MB each) would make the gallery unusable on mobile.

    Moderation flow:
      pending -> approved  (moderator accepts)
      pending -> rejected  (moderator rejects)
    Only approved photos are visible to event participants.
    """

    __tablename__ = "photos"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    gallery_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("galleries.id", ondelete="CASCADE"), nullable=False, index=True
    )
    uploader_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True
    )

    # S3 keys — only the key is stored, the base URL comes from config
    original_s3_key: Mapped[str] = mapped_column(String(512), nullable=False)
    # NULL until the thumbnail generation worker completes
    thumbnail_s3_key: Mapped[Optional[str]] = mapped_column(String(512), nullable=True)

    # Original file metadata (populated at upload time)
    original_filename: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    # File size in bytes — useful for storage quotas and UI display
    file_size_bytes: Mapped[Optional[int]] = mapped_column(BigInteger, nullable=True)
    # MIME type, e.g. 'image/jpeg', 'image/heic'
    mime_type: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    # Pixel dimensions of the original
    width_px: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    height_px: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    # Moderation
    moderation_status: Mapped[str] = mapped_column(
        SAEnum("pending", "approved", "rejected", name="photo_moderation_status_enum"),
        nullable=False,
        server_default="pending",
        index=True,
    )
    moderation_comment: Mapped[Optional[str]] = mapped_column(String(512), nullable=True)
    moderated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    moderated_by_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )

    # Sort order within the gallery (can be updated by organizer)
    sort_order: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")

    deleted_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    gallery: Mapped["Gallery"] = relationship("Gallery", back_populates="photos")
    uploader: Mapped[Optional["User"]] = relationship(
        "User", foreign_keys=[uploader_id], back_populates="photos"
    )
    moderated_by: Mapped[Optional["User"]] = relationship(
        "User", foreign_keys=[moderated_by_id], back_populates="moderated_photos"
    )

    __table_args__ = (
        CheckConstraint("file_size_bytes > 0", name="ck_photos_file_size_positive"),
        CheckConstraint("width_px > 0", name="ck_photos_width_positive"),
        CheckConstraint("height_px > 0", name="ck_photos_height_positive"),
        # Fast fetch of the approved gallery feed, ordered by upload time
        Index(
            "ix_photos_gallery_approved",
            "gallery_id",
            "created_at",
            postgresql_where="moderation_status = 'approved' AND deleted_at IS NULL",
        ),
        # Moderation queue index — find pending photos quickly
        Index(
            "ix_photos_pending_moderation",
            "gallery_id",
            "created_at",
            postgresql_where="moderation_status = 'pending' AND deleted_at IS NULL",
        ),
    )
